[technote]
id = "SQR-108"
series_id = "SQR"
canonical_url = "https://sqr-108.lsst.io"
github_url = "https://github.com/lsst-sqre/sqr-108"
github_default_branch = "main"
date_created = 2025-10-16T14:48:32Z
organization.name = "NSF-DOE Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[[technote.authors]]
internal_id = "fuchsds"
orcid = "https://orcid.org/0009-0007-2454-1951"
name = {given = "Dan C.", family = "Fuchs"}
[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC"
address = "Menlo Park"
ror = "https://ror.org/05gzmn429"
